package model;

public enum CommandType {
    LOOK, GO, ADD_HEALTH, 
    SET_NAME, SET_SHORT_DESC, SET_DESC, ADD_ITEM, REMOVE_ITEM,
    SET_NAME_OF, SET_SHORT_DESC_OF, SET_DESC_OF, ADD_ITEM_TO, REMOVE_ITEM_FROM,
    PRINT
}
